#!/bin/bash

#
# prompts user to enter a confirmation character
#   $1 is the message to be shown
#   returns 0 if confirmed, 1 elsecase

function confirm () {
  read -p "$1 [y/N]: " -n 1 -r REPLY
  echo
  [[ "$REPLY" =~ ^[Yy]$ ]] && return 0 || return 1
}

#
# prompts user to press a key to continue
function wait_key () {
  read -p "Press any key to proceed or Ctrl^C to abort..." -n 1 -s && echo
}

#
# executes a file
# Optionally asks to make the file executable if it's not
# $1 is the file to be executed

function exec_file () {
  FILE="$1"
  echo
  #echo "executing '$FILE'..."
  if [ ! -x $FILE ]
  then
    echo "Can't execute this entry because it's not executable"
    confirm "Do you want to make it executable now?" && chmod +x $FILE\
    || ( echo "Can't execute then." && wait_key && return 0 )
  fi
  $FILE || ( echo "Execution failed" && wait_key && return 1 )
  return 0
}

function print_md () {
  [ -f "$1" ] || return 1
  echo "/**"
  while read
  do
    echo " * $REPLY"
  done < "$1"
  echo " */"
}

function prompt_menu () {
  [ ! -d $DIR ] && echo "$1 is not a directory" && wait_key && exit 1
  local DIR="$1"

  if [ "$DIR" = "$MAIN_MENU" ]
  then
    local BACK+="Quit"
  else
    local BACK+="Back"
  fi

  if [ -n "$2" ]
  then
    local MODE="$2"
    local OPTIONS="$BACK $(ls --format=single-column $DIR | grep -v README.md | tr " " "_" | tr "\n" " ")"
  else
    local MODE="Listing files at '$1'"
    local OPTIONS="$BACK $(ls --format=single-column $DIR | tr " " "_" | tr "\n" " ")"
  fi

  clear
  echo "/**"
  echo " * # iai-ide #"
  echo " *"
  echo " * $MODE"
  echo " *"
  echo " * \$WORKSPACE=$WORKSPACE"
  [ ! -f "${WORKSPACE}/package.json" ] && echo " * The workspace is not a node.js package"
  [ -n "$RESOURCE" ] && echo " * \$RESOURCE=$RESOURCE"
  echo " */"
  echo

  echo "Select an option:"
  select opt in $OPTIONS
  do
    if [ "$opt" = "$BACK" ]
    then
      [ "$BACK" = "Quit" ] && clear && echo "Bye." && exit 0
      return 1
    fi

    SELECTED="${DIR}/${opt}"
    if [ -n "$opt" -a -a "$SELECTED" ]
    then
      return 0
    elif [ -a "${DIR}/$(echo $opt | tr "_" " ")" ]
    then
      SELECTED="${DIR}/$(echo $opt | tr "_" " ")"
      return 0
    else
      echo "Input the number of an option above or hit enter to see the options"
      echo "opt=$opt"
      echo "OPTION=$OPTION"
    fi
  done
}

function exec_menu () {
  if [ -f "$1" ]
  then
    exec_file "$1" && return 0 || return 1
  elif [ -d "$1" ]
  then
    #echo "exec menu $1" && wait_key
    while prompt_menu "$1" "$2"
    do
      exec_menu $SELECTED || break
    done
    return 1
  else
    echo "Unsuported file type."
    echo "1=${1}"
    wait_key
    return 1
  fi
}

#
# bootstraping
#

PS3="iai> "

# store current directory as WORKSPACE and iai-ide directory
WORKSPACE=$(pwd)
IAI_DIR="$(dirname $(readlink -f "${BASH_SOURCE}"))"

MAIN_MENU="${IAI_DIR}/main-menu"
exec_menu "$MAIN_MENU" "Main menu"