#!/bin/bash

# directory where the resource directory will be created
SAVES_TO=$(pwd)

clear
echo "/**"
echo " * # html5document boilerplate #"
echo " *"
echo " * Based on the work by the html5boilerplate community (see html5boilerplate.com)"
echo " *"
echo " * At first, this boilerplate will ask for the resource name."
echo " *"
echo " * Then it will dowload the index.html file from the h5bp github"
echo " * repository and prompt you for modifications."
echo " *"
echo " * The resource will be saved as a directory on $SAVES_TO"
echo " */"
echo

#
# asks user for the resource name

read_name () {
  read -p "resource_name: " NAME
  RESOURCE="${SAVES_TO}/$(echo $NAME | tr " " "\ ")"
  if [ -a "$RESOURCE" ]
  then
    echo "resource_name '$NAME' already exists."
    read_name
  fi
}

#
# actions of the boilerplate

read_name

echo
echo "New html5 document will be saved to $RESOURCE"
read -p "Press any key to proceed or Ctrl^C to abort..." -n 1 -s

echo
wget -O "$RESOURCE" https://raw2.github.com/h5bp/html5-boilerplate/master/index.html

#echo
#echo "New html5 document will be opened on vim"
#read -p "Press any key to continue..." -n 1 -s
#vim "$RESOURCE"

echo
